### ISSUE TITLE
python image

### ISSUE THREAD

**Issue by chdanielmueller** [jaydensmith/alpine-python-wkhtmltopdf#1]
Hi Jayden,

I saw that you forked https://github.com/Surnet/alpine-node-wkhtmltopdf and created this repo. :+1:
I hope the Dockerfile served you well as a base for this.

I wanted to inform you that I moved my Dockerfile creation logic to a seperate repo.
https://github.com/Surnet/docker-wkhtmltopdf

It also creates a python image (with and without wkhtmltoimage).
If you want to update to python 3.6.4 and alpine 3.7 please don't bother with the needed changes and check the following file out:
https://github.com/Surnet/docker-wkhtmltopdf/blob/master/archive/alpine-python-wkhtmltopdf/Dockerfile_3.6.4-0.12.4-full

Cheers,
Daniel

**Comment by jaydensmith** [comment]
Thanks @chdanielmueller, that's a lot better than my own.
Assuming my project works with Python 3.6.x I'll give that a go instead.

**Comment by chdanielmueller** [comment]
Nice.
If there is anything I can help you with in regard of the image just contact me/open a issue on the repo.
